spring:
    datasource:
        url: jdbc:mysql://123.57.240.11:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: youyou
        password: youyouPassw0rd
        #连接池的配置信息
        initialSize: 50
        minIdle: 50
        maxActive: 500
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        removeAbandonedTimeout: 180000
        removeAbandoned: true

        # Druid 配置
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

    redis:
        host: redis-master.dev.svc.cluster.local
        port: 6379
        pool:
            max-active: 10000
            max-wait: 60000
            max-idle: 100
            timeout: 60000
